# Generated by Django 4.2.7 on 2026-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="帖子标题（5-100字符）", max_length=100)),
                ("content", models.TextField(help_text="帖子内容（支持富文本）")),
                (
                    "author_id",
                    models.IntegerField(help_text="作者ID（关联M1 users_auth.id）"),
                ),
                ("section_id", models.IntegerField(help_text="板块ID（关联M5 sections.id）")),
                (
                    "is_pinned",
                    models.BooleanField(db_index=True, default=False, help_text="是否置顶"),
                ),
                (
                    "pin_type",
                    models.CharField(
                        choices=[
                            ("none", "未置顶"),
                            ("global", "全局置顶"),
                            ("section", "板块置顶"),
                        ],
                        db_index=True,
                        default="none",
                        help_text="置顶类型",
                        max_length=20,
                    ),
                ),
                ("views_count", models.IntegerField(default=0, help_text="浏览量")),
                ("replies_count", models.IntegerField(default=0, help_text="回复数")),
                ("likes_count", models.IntegerField(default=0, help_text="点赞数")),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "已发布"), ("deleted", "已删除")],
                        db_index=True,
                        default="published",
                        help_text="帖子状态",
                        max_length=20,
                    ),
                ),
                ("edit_count", models.IntegerField(default=0, help_text="编辑次数")),
                (
                    "last_edited_at",
                    models.DateTimeField(blank=True, help_text="最后编辑时间", null=True),
                ),
                (
                    "last_edited_by",
                    models.IntegerField(blank=True, help_text="最后编辑者ID", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
            ],
            options={
                "verbose_name": "帖子",
                "verbose_name_plural": "帖子",
                "db_table": "posts",
                "ordering": ["-is_pinned", "-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostEditHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("section_id", models.IntegerField()),
                ("edited_by", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "编辑历史",
                "verbose_name_plural": "编辑历史",
                "db_table": "post_edit_history",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
