# Generated by Django 4.2.7 on 2026-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostFavorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post_id", models.IntegerField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_favorites",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post_id", models.IntegerField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_likes",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_id",
                    models.IntegerField(db_index=True, help_text="帖子ID（关联 posts.id）"),
                ),
                (
                    "author_id",
                    models.IntegerField(
                        db_index=True, help_text="作者ID（关联 users_auth.id）"
                    ),
                ),
                (
                    "parent_id",
                    models.IntegerField(
                        blank=True, db_index=True, help_text="父回复ID", null=True
                    ),
                ),
                ("content", models.TextField(help_text="回复内容（2-10000字符）")),
                ("floor_number", models.IntegerField(help_text="楼层号")),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否已删除"
                    ),
                ),
                ("edit_count", models.IntegerField(default=0, help_text="编辑次数")),
                (
                    "last_edited_at",
                    models.DateTimeField(blank=True, help_text="最后编辑时间", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
            ],
            options={
                "verbose_name": "回复",
                "verbose_name_plural": "回复",
                "db_table": "replies",
                "ordering": ["post_id", "floor_number"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReplyLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reply_id", models.IntegerField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reply_likes",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShareRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post_id", models.IntegerField(db_index=True)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("share_type", models.CharField(default="link", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "share_records",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("posts_count", models.IntegerField(default=0)),
                ("followers_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topics",
                "ordering": ["-posts_count"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TopicFollow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(db_index=True)),
                ("topic_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topic_follows",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("follower_id", models.IntegerField(db_index=True)),
                ("following_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_follows",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
