serverAddr = "47.104.67.179"
serverPort = 7000
loginFailExit = false

webServer.addr = "127.0.0.1"
webServer.port = 7400

transport.protocol = "tcp"
transport.poolCount = 20
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 15
transport.heartbeatInterval = 15
transport.heartbeatTimeout = 45
transport.dialServerTimeout = 5
transport.dialServerKeepalive = 30
transport.tls.enable = true

auth.method = "token"
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "/etc/frp/token"

log.to = "console"
log.level = "info"
log.disablePrintColor = true

[[proxies]]
name = "open436-public-web"
type = "tcp"
localIP = "open436-prod-public-web"
localPort = 80
remotePort = 18080
transport.useEncryption = true

[proxies.healthCheck]
type = "http"
path = "/"
intervalSeconds = 10
timeoutSeconds = 3
maxFailed = 3

[[proxies]]
name = "open436-admin-web"
type = "tcp"
localIP = "open436-prod-admin"
localPort = 80
remotePort = 18081
transport.useEncryption = true

[proxies.healthCheck]
type = "http"
path = "/"
intervalSeconds = 10
timeoutSeconds = 3
maxFailed = 3

[[proxies]]
name = "open436-ssh"
type = "tcp"
localIP = "172.20.193.162"
localPort = 22
remotePort = 16022
transport.useEncryption = true

[proxies.healthCheck]
type = "tcp"
intervalSeconds = 10
timeoutSeconds = 3
maxFailed = 3
