use_default_settings: true

general:
  debug: false
  instance_name: "Open436 SearXNG"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "open436-searxng-secret-key-2026"
  limiter: false

outgoing:
  request_timeout: 10
  max_request_timeout: 15

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: baidu
    engine: baidu
    shortcut: bd
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
